version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git   # (1)
    working_directory: ~/ds-circleci-images
    steps:
      - checkout
      - setup_remote_docker   # (2)

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t developmentseed/circleci:node8.4-python2.7 - < images/node8.4-python2.7
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push developmentseed/circleci:node8.4-python2.7
