version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git   # (1)
    working_directory: ~/ds-circleci-images
    steps:
      - checkout
      - setup_remote_docker   # (2)

      # build and push Docker image
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

           docker build -t developmentseed/circleci:node12.2-awscli - < images/node12.2-awscli
           docker push developmentseed/circleci:node12.2-awscli
